services:
  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    image: frontend:latest
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API=http://localhost:8000/api/v1
    depends_on:
      - backend